services:
  mosaic:
    extends:
      file: compose.yml
      service: mosaic
    volumes:
      - ./containers/mosaic/dist:/app/dist
  sb8:
    extends:
      file: compose.yml
      service: sb8
    volumes:
      - ./containers/mosaic/src:/mosaic/src
      - ./containers/sb-8/stories:/app/stories
    ports:
      - 10001:10001
volumes:
  sv-mosaic-lib:
