services:
  mosaic:
    build: ./containers/mosaic
    volumes:
      - sv-mosaic-lib:/app
      - ./containers/mosaic/dist:/app/dist
  mosaic-types:
    build: ./containers/mosaic-types
    volumes:
      - ./containers/mosaic/dist/types:/app/types
    depends_on:
      - mosaic
  sb5:
    build: ./containers/sb-5
    volumes:
      - sv-mosaic-lib:/mosaic
      - ./containers/mosaic/src:/mosaic/src
    ports:
      - "10000:10000"
    depends_on:
      - mosaic
  sb8:
    build: ./containers/sb-8
    volumes:
      - sv-mosaic-lib:/mosaic
      - ./containers/mosaic/src:/mosaic/src
      - ./containers/sb-8/stories:/app/stories
      - ./containers/sb-8/storybook-static:/app/storybook-static
    ports:
      - "10001:10001"
    depends_on:
      - mosaic
volumes:
  sv-mosaic-lib:
