services:
  mosaic:
    container_name: mosaic
    build: ./containers/mosaic
    volumes:
      - sv-mosaic-lib:/app
      - ./containers/mosaic/dist:/app/dist
  mosaic-types:
    container_name: mosaic-types
    build: ./containers/mosaic-types
    volumes:
      - ./containers/mosaic/dist/types:/app/types
    depends_on:
      - mosaic
  sb5:
    build: ./containers/sb-5
    volumes:
      - sv-mosaic-lib:/mosaic
      - ./containers/mosaic/src:/mosaic/src
    ports:
      - "10000:10000"
    depends_on:
      - mosaic
  sb8:
    build: ./containers/sb-8
    volumes:
      - sv-mosaic-lib:/mosaic
      # We need this in development, so maybe have two different compose files?
      # https://docs.docker.com/compose/multiple-compose-files/extends/
      # - ./containers/mosaic/src:/mosaic/src
      # - ./containers/sb-8/stories:/app/stories
      # - ./containers/sb-8/storybook-static:/app/storybook-static
    ports:
      - "10001:10001"
    depends_on:
      - mosaic
  sb-server:
    container_name: sb-server
    image: node:18.18.2
    working_dir: /app
    command: npx --yes http-server ./storybook-static -p 10001 --silent
    ports:
      - "10001:10001"
  e2e-tests:
    container_name: e2e-tests
    build: ./containers/e2e-tests
    working_dir: /app
    command: npm start
    depends_on:
      - mosaic
    volumes:
      - sv-mosaic-lib:/mosaic
  publisher:
    build: ./containers/publisher
    depends_on:
      - sb8
    tty: true
volumes:
  sv-mosaic-lib:
