version: 2.1

jobs:
  unit_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - run:
          name: Run tests
          command: |
            docker-compose build mosaic
            docker-compose run --name sv-mosaic mosaic yarn test
  build_dist:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - run:
          name: Build Mosaic distribution
          command: |
            docker-compose build mosaic
            docker-compose run --name sv-mosaic mosaic yarn build
      - run:
          name: Extract dist files
          command: |
            docker cp sv-mosaic:/app/dist dist
  build_sb_static:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - run:
          name: Build static Storybook files
          command: |
            docker-compose build mosaic
            docker-compose build sb8
            docker-compose run --name sv-mosaic-sb8 sb8 yarn build
      - run:
          name: Extract static files
          command: |
            docker cp sv-mosaic-sb8:/app/storybook-static storybook-static
      - persist_to_workspace:
          root: ~/project
          paths:
              - storybook-static
  publish_sb_static:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - 90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50
      - run:
          name: Spin up publishing container
          command: |
            docker-compose build mosaic
            docker-compose build publisher
            docker-compose run --name sv-mosaic-publisher publisher
      - run:
          name: Copy SSH
          command: |
            # Copy base container's .ssh to publishing container's .ssh
            docker cp ~/.ssh sv-mosaic-publisher:/root/.ssh
            # Give ~/.ssh and the keys inside the correct ownership and permissions
            docker exec -t sv-mosaic-publisher sh -c "chmod 700 ~/.ssh && chmod 600 ~/.ssh/* && chown -R root:root ~/.ssh"
            # Replace the base container's home path with the publishing container's home path in the .ssh/config file
            docker exec -t sv-mosaic-publisher sh -c "sed -i 's#/home/circleci#/root#g' /root/.ssh/config"
      - run:
          name: Add github to known_hosts
          command: docker exec -t github-pages sh -c "ls -la ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts"



workflows:
  main:
    jobs:
      - build_sb_static:
          context: default
          filters:
            branches:
              only:
                - sb-upgrade
      - publish_sb_static:
          context: default
          requires:
            - build_sb_static
          filters:
            branches:
              only:
                - sb-upgrade
