version: 2.1

jobs:
  unit_tests:
    docker:
      - image: cimg/base:2021.04
        name: unit_tests
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - run:
          name: Run tests
          command: |
            docker-compose build mosaic
            docker-compose run --name sv-mosaic mosaic yarn test
  build_dist:
    docker:
      - image: cimg/base:2021.04
        name: unit_tests
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - run:
          name: Build Mosaic distribution
          command: |
            docker-compose build mosaic
            docker-compose run --name sv-mosaic mosaic yarn build
      - run:
          name: List container files
          command: |
            docker-compose run mosaic ls -la
      - run:
          name: List containers
          command: |
            docker ps -a
      - run:
          name: Extract dist files
          command: |
            docker cp sv-mosaic:/app/dist dist
      - run:
          name: List files
          command: |
            ls -la

workflows:
  main:
    jobs:
      - build_dist:
          context: default
          filters:
            branches:
              only:
                - /pull.*/
