version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app

workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
