version: 2.1
orbs:
  node: circleci/node@5.0.2

commands:
  load_mosaic_image:
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Load Mosaic Docker image
          command: |
            docker load \
            -i \
            sv_mosaic_build.tar

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
        name: build
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Build Mosaic Docker image
          command: |
            DOCKER_BUILDKIT=1 \
            docker build \
            -t "sv-mosaic" \
            .
      - run:
          name: Save Mosaic Docker image
          command: |
            docker save \
            -o sv_mosaic_build.tar \
            sv-mosaic
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  unit_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - load_mosaic_image
      - run:
          name: Spin up container and run unit tests
          command: |
            docker run \
            sv-mosaic \
            yarn test:ci
      - store_test_results:
          path: ./reports/
  storybook:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - add_ssh_keys:
          fingerprints:
            - "90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50"
      - load_mosaic_image
      - run:
          name: Spin up container
          command: |
            docker run \
              -v ~/.ssh:/root/.ssh \
              -e CIRCLE_BRANCH=${CIRCLE_BRANCH} \
              sv-mosaic \
              sh -c "ssh-keyscan github.com >> ~/.ssh/known_hosts && ls -la /root/.ssh"

# workflows:
#   build:
#     jobs:
#       - build:
#           context: default
#           filters:
#             branches:
#               only:
#                 - develop
#                 - /pull.*/
#       - unit_tests:
#           context: default
#           requires:
#             - build
#           filters:
#             branches:
#               only:
#                 - develop
#                 - /pull.*/
#       - storybook:
#           context: default
#           filters:
#             branches:
#               only:
#                 - develop
#                 - /pull.*/
#           requires:
#             - unit_tests

workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - unit_tests:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - storybook:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - develop
