version: 2.1
orbs:
  node: circleci/node@5.0.2
  envsubst: sawadashota/envsubst@volatile

jobs:
  build:
    executor: node/default
    steps:
      - envsubst/install
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  storybook:
    executor: node/default
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - 90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50
      - run:
          name: Add github to known_hosts
          command: |
            mkdir -p ~/.ssh/
            chmod 700 ~/.ssh/
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Publish storybook
          command: yarn run ci:storybook
          environment:
            NODE_DEBUG: gh-pages
  unit_tests:
    executor: node/default
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Unit Tests
          command: yarn test


workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - unit_tests:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - storybook:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
          requires:
            - build
