version: 2.1

jobs:
  public_build:
    docker:
      - image: cimg/base:2021.04
        name: build
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Build public image
          command: DOCKER_BUILDKIT=1 docker build -t "sv-mosaic" .
      - run:
          name: Save public image
          command: docker save -o sv_mosaic_build.tar sv-mosaic
      - persist_to_workspace:
          root: ~/project
          paths:
            - sv_mosaic_build.tar
            - scripts
  unit_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Load public image
          command: docker load -i sv_mosaic_build.tar
      - run:
          name: Spin up sub-container
          command: chmod +x ./scripts/run-capture-id && ./scripts/run-capture-id
      - run:
          name: Run tests
          command: docker exec $CONTAINER_ID yarn test:ci
      - run:
          name: Extract reports
          command: docker cp $CONTAINER_ID:/app/reports ~/reports
      - store_test_results:
          path: ~/reports
  e2e_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Load public image
          command: docker load -i sv_mosaic_build.tar
      - run:
          name: List dir
          command: pwd && ls -la .
      - run:
          name: Spin up sub-containers and run tests
          command: cd automation_testing && docker-compose up

workflows:
  build:
    jobs:
      - public_build:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - unit_tests:
          context: default
          requires:
            - public_build
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - e2e_tests:
          context: default
          requires:
            - public_build
          filters:
            branches:
              only:
                - develop
                - /pull.*/
