version: 2.1
workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - master
                - qa
                - staging
      - publish:
          requires:
            - build
          context: default
      - notify:
          requires:
            - storybook
            - publish
          context: default
      - storybook:
          requires:
            - build
          context: default

orbs:
  slack: circleci/slack@4.4.0
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export IMAGE="gcr.io/sv-shared-231700/sv-mosaic:${CIRCLE_BRANCH}"' >> $BASH_ENV
      - run:
          name: Docker build
          command: |
            docker login -u _json_key -p "${GCLOUD_SERVICE_KEY}" https://gcr.io
            docker pull $IMAGE || true
            DOCKER_BUILDKIT=1 docker build -t $IMAGE --cache-from $IMAGE .
            docker push $IMAGE
      # - run:
      #     name: Prepublish NPM
      #     command: docker run -e CIRCLE_BRANCH -e CIRCLE_SHA1 sv-mosaic:local yarn run ci:prepublish
      # - slack/notify:
      #     channel: GT3L59FHP
      #     event: fail
      #     template: basic_fail_1
      # - slack/notify:
      #     channel: GT3L59FHP
      #     event: pass
      #     template: basic_success_1
  publish:
    docker:
      - image: gcr.io/sv-shared-231700/sv-mosaic:${CIRCLE_BRANCH}
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    working_directory: /app
    steps:
      - run:
          name: Publish to NPM
          command: yarn run ci:publish
  storybook:
    docker:
      - image: gcr.io/sv-shared-231700/sv-mosaic:${CIRCLE_BRANCH}
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    working_directory: /app
    steps:
      - add_ssh_keys:
          fingerprints:
            - 90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50
      - run:
          name: Add github to known_hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Publish storybook
          command: yarn run ci:storybook
          environment:
            NODE_DEBUG: gh-pages
  notify:
    docker:
      - image: cimg/base:2021.04
    steps:
      - slack/notify:
          channel: GT3L59FHP
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: GT3L59FHP
          event: pass
          template: basic_success_1
