version: 2.1
orbs:
  node: circleci/node@5.0.2
  envsubst: sawadashota/envsubst@volatile

jobs:
  build:
    executor: node/default
    steps:
      - envsubst/install
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace
        root: ~/project
        paths:
          - .
  test:
    executor: node/default
    steps:
      - attach_workspace
        at: ~/project
      - run:
        command: yarn test


workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - test:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
