version: 2.1

commands:
  init:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23

jobs:
  Unit Tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - init
      # - run:
      #     name: Run tests
      #     command: |
      #       docker-compose build mosaic
      #       docker-compose run --name sv-mosaic mosaic yarn test
  E2E Tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - init
      # - attach_workspace:
      #     at: ~/project
      # - run:
      #     name: Spin up containers
      #     command: |
      #       docker-compose build mosaic sb-server e2e-tests
      #       docker-compose up -d mosaic sb-server e2e-tests
      # - run:
      #     name: Copy Storybook static files
      #     command: docker cp storybook-static sb-server:/app/storybook-static
      # - run:
      #     name: Mark server as ready
      #     command: docker-compose exec sb-server touch /app/storybook-static/ready
      # - run:
      #     name: Attach to container
      #     command: docker container attach e2e-tests
  Build Mosaic Dist:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - init
      - run:
          name: Build Mosaic distribution
          command: |
            docker-compose build mosaic
            docker-compose run --name sv-mosaic mosaic yarn build
      - run:
          name: Extract dist files
          command: |
            docker cp sv-mosaic:/app/dist dist
      - persist_to_workspace:
          root: ~/project
          paths:
              - dist
  Build SB Static:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - init
      - run:
          name: Build static Storybook files
          command: |
            docker-compose build mosaic
            docker-compose build sb8
            docker-compose run --name sv-mosaic-sb8 sb8 yarn build
      - run:
          name: Extract static files
          command: |
            docker cp sv-mosaic-sb8:/app/storybook-static storybook-static
      - persist_to_workspace:
          root: ~/project
          paths:
              - storybook-static
  Publish SB Static:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - init
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - 90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50
      - run:
          name: Spin up publishing container
          command: |
            docker-compose build publisher
            docker-compose run -d -e CIRCLE_BRANCH=${CIRCLE_BRANCH} --name sv-mosaic-publisher publisher
      - run:
          name: Copy SSH
          command: |
            # Copy base container's .ssh to publishing container's .ssh
            docker cp ~/.ssh sv-mosaic-publisher:/root/.ssh
            # Give ~/.ssh and the keys inside the correct ownership and permissions
            docker exec -t sv-mosaic-publisher sh -c "chmod 700 ~/.ssh && chmod 600 ~/.ssh/* && chown -R root:root ~/.ssh"
            # Replace the base container's home path with the publishing container's home path in the .ssh/config file
            docker exec -t sv-mosaic-publisher sh -c "sed -i 's#/home/circleci#/root#g' /root/.ssh/config"
      - run:
          name: Add github to known_hosts
          command: docker exec -t sv-mosaic-publisher sh -c "ls -la ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts"
      - run:
          name: Copy static files into container
          command: docker cp storybook-static sv-mosaic-publisher:/app/docs/sb8
      - run:
          name: Publish to Github pages
          command: docker exec -t sv-mosaic-publisher yarn publish:github-pages
  Publish to NPM:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - init
      - attach_workspace:
          at: ~/project
      - run:
          name: Publish @simpleview/sv-mosaic
          command: |
            docker-compose build mosaic
            docker-compose up mosaic
            docker cp dist/. mosaic:/app/dist
            docker-compose run mosaic find /app -maxdepth 2
            # docker-compose run -e CIRCLE_BRANCH=${CIRCLE_BRANCH} -e CIRCLE_SHA1=${CIRCLE_SHA1} -e NPM_TOKEN=${NPM_TOKEN} mosaic yarn publish:npm
      - run:
          name: Publish @simpleview/sv-mosaic-types
          command: |
            docker-compose build mosaic-types
            docker-compose up mosaic-types
            docker-compose run mosaic-types cp -r /mosaic/dist/types /app/types
            docker-compose run mosaic sh -c "find /mosaic -maxdepth 2 && find /app -maxdepth 2"
            # docker-compose run -e CIRCLE_BRANCH=${CIRCLE_BRANCH} -e CIRCLE_SHA1=${CIRCLE_SHA1} -e NPM_TOKEN=${NPM_TOKEN} mosaic-types yarn publish:npm

workflows:
  main:
    jobs:
      # - Unit Tests:
      #     context: default
      #     filters:
      #       branches:
      #         only:
      #           - sb-upgrade
      - Build Mosaic Dist:
          context: default
          filters:
            branches:
              only:
                - sb-upgrade
      - Build SB Static:
          context: default
          filters:
            branches:
              only:
                - sb-upgrade
      # - E2E Tests:
      #     context: default
      #     requires:
      #       - Build SB Static
      #     filters:
      #       branches:
      #         only:
      #           - sb-upgrade
      # - Publish SB Static:
      #     context: default
      #     requires:
      #       - Build SB Static
      #       - Unit Tests
      #       - E2E Tests
      #     filters:
      #       branches:
      #         only:
      #           - sb-upgrade
      - Publish to NPM:
          context: default
          requires:
            - Build Mosaic Dist
            # - Unit Tests
            # - E2E Tests
          filters:
            branches:
              only:
                - sb-upgrade
