version: 2.1

commands:
  load_public_build:
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Load public image
          command: docker load -i sv_mosaic_build.tar

jobs:
  public_build:
    docker:
      - image: cimg/base:2021.04
        name: build
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Build public image
          command: DOCKER_BUILDKIT=1 docker build -t "sv-mosaic" .
      - run:
          name: Save public image
          command: docker save -o sv_mosaic_build.tar sv-mosaic
      - persist_to_workspace:
          root: ~/project
          paths:
            - sv_mosaic_build.tar
            - scripts
  unit_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - load_public_build
      - run:
          name: Spin up sub-container
          command: |
            docker container create -t --name sv-mosaic sv-mosaic
            docker container start sv-mosaic
      - run:
          name: Run tests
          command: docker exec sv-mosaic yarn test:ci
      - run:
          name: Extract reports
          command: docker cp sv-mosaic:/app/reports ~/reports
      - store_test_results:
          path: ~/reports
  e2e_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - load_public_build
      - run:
          name: Spin up test containers
          command: cd automation_testing && docker-compose up --detach
      - run:
          name: Copy tests to container
          command: |
            docker cp ./automation_testing sv-mosaic-e2e:/app/automation_testing
            docker exec sv-mosaic-e2e chmod +x automation_testing/scripts/try-storybook
            docker exec sv-mosaic-e2e mkdir /app/src
            docker cp ./src/theme sv-mosaic-e2e:/app/src/theme
      - run:
          name: List dir
          command: docker exec sv-mosaic-e2e ls -la ./automation_testing
      - run:
          name: Run tests
          command: docker exec sv-mosaic-e2e ./automation_testing/scripts/try-storybook
  storybook:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - load_public_build
      - add_ssh_keys:
          fingerprints:
            - 90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50
      - run:
          name: Spin up publishing container
          command: docker run --name sv-mosaic -e CIRCLE_BRANCH=${CIRCLE_BRANCH} -t -d sv-mosaic
      - run:
          name: Copy SSH
          command: |
            # Copy base container's .ssh to publishing container's .ssh
            docker cp ~/.ssh sv-mosaic:/root/.ssh
            # Give ~/.ssh and the keys inside the correct ownership and permissions
            docker exec -t sv-mosaic sh -c "chmod 700 ~/.ssh && chmod 600 ~/.ssh/* && chown -R root:root ~/.ssh"
            # Replace the base container's home path with the publishing container's home path in the .ssh/config file
            docker exec -t sv-mosaic sh -c "sed -i 's#/home/circleci#/root#g' /root/.ssh/config"
      - run:
          name: Add github to known_hosts
          command: docker exec -t sv-mosaic sh -c "ls -la ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts"
      - run:
          name: Publish to GitHub pages
          command: docker exec -t sv-mosaic yarn run ci:storybook
  publish:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - load_public_build
      - run:
          name: Spin up publishing container
          command: docker run --name sv-mosaic -e CIRCLE_BRANCH=${CIRCLE_BRANCH} -e CIRCLE_SHA1=${CIRCLE_SHA1} -e NPM_TOKEN=${NPM_TOKEN} -t -d sv-mosaic
      - run:
          name: Publish to NPM
          command: docker exec -t sv-mosaic yarn run ci:publish

workflows:
  build:
    jobs:
      - public_build:
          context: default
          filters:
            branches:
              only:
                - ci-testing
      - unit_tests:
          context: default
          requires:
            - public_build
          filters:
            branches:
              only:
                - ci-testing
      - e2e_tests:
          context: default
          requires:
            - public_build
          filters:
            branches:
              only:
                - ci-testing
      - storybook:
          context: default
          requires:
            - public_build
            # Require tests be done before sending to GH pages
            - unit_tests
            - e2e_tests
          filters:
            branches:
              only:
                # - ci-testing
                foo
      - publish:
          context: default
          requires:
            - public_build
            # Require tests be done and successful publish to GH
            # pages happened before sending to NPM
            - unit_tests
            - e2e_tests
            - storybook
          filters:
            branches:
              only:
                # - ci-testing
                foo
