version: 2.1
workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - master
                - qa
                - staging
orbs:
  slack: circleci/slack@4.4.0
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50"
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - run:
          name: Docker build
          command: docker build . -t sv-mosaic:local
      - run:
          name: debug
          command: ls -l ~/.ssh && cat ~/.ssh/config
      - run:
          name: Publish storybook
          command: docker run -e CIRCLE_BRANCH -e CIRCLE_SHA1 -v /home/circleci/.ssh:/root/.ssh sv-mosaic:local ls -l /root/.ssh
      # - run:
      #     name: Prepublish NPM
      #     command: docker run -e CIRCLE_BRANCH -e CIRCLE_SHA1 sv-mosaic:local yarn run ci:prepublish
      # - slack/notify:
      #     channel: GT3L59FHP
      #     event: fail
      #     template: basic_fail_1
      # - slack/notify:
      #     channel: GT3L59FHP
      #     event: pass
      #     template: basic_success_1
