version: 2.1

jobs:
  unit_tests:
    docker:
      - image: cimg/base:2021.04
        name: unit_tests
    resource_class: large
    steps:
      - run:
          name: Run tests
          command: ls -la
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - run:
          name: Run tests
          command: |
            docker-compose build mosaic
            docker-compose run mosaic yarn test

workflows:
  main:
    jobs:
      # Pull request branches and the develop branch have tests run for them
      - unit_tests:
          context: default
          filters:
            branches:
              only:
                - /pull.*/
