version: 2.1

jobs:
  unit_tests:
    docker:
      - image: cimg/base:2021.04
        name: unit_tests
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - run:
          name: Run tests
          command: |
            docker-compose build mosaic
            docker-compose run --name sv-mosaic mosaic yarn test
  build_dist:
    docker:
      - image: cimg/base:2021.04
        name: unit_tests
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - run:
          name: Build Mosaic distribution
          command: |
            docker-compose build mosaic
            docker-compose run --name sv-mosaic mosaic yarn build
      - run:
          name: Extract dist files
          command: |
            docker cp sv-mosaic:/app/dist dist
  build_sb_static:
    docker:
      - image: cimg/base:2021.04
        name: unit_tests
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker23
      - run:
          name: Build static Storybook files
          command: |
            docker-compose build mosaic
            docker-compose build sb8

            docker-compose run sb8 sh -c "ls -la ../mosaic/src"
            docker-compose run sb8 yarn build
      - run:
          name: Extract static files
          command: |
            docker cp sv-mosaic-sb8:/app/storybook-static storybook-static
      - run:
          name: List directory
          command: |
            ls -la storybook-static

workflows:
  main:
    jobs:
      - build_sb_static:
          context: default
          filters:
            branches:
              only:
                - /pull.*/
