version: 2.1
orbs:
  node: circleci/node@5.0.2
  envsubst: sawadashota/envsubst@volatile

jobs:
  build:
    executor: node/default
    steps:
      - envsubst/install
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  unit_tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Unit Tests
          command: yarn test


workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - unit_tests:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /pull.*/
