version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
        name: build
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Docker build
          command: |
            DOCKER_BUILDKIT=1 docker build -t "sv-mosaic" .
            docker save -o sv_mosaic_build.tar sv-mosaic
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  unit_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Load docker image
          command: docker load -i sv_mosaic_build.tar
      - run:
          name: List images
          command: docker image ls
      - run:
          name: Run Tests
          command: docker run sv-mosaic yarn test
  # build:
  #   executor:
  #     name: node/default
  #     tag: '16.14.2'
  #   steps:
  #     - envsubst/install
  #     - checkout
  #     - node/install-packages:
  #         pkg-manager: yarn
  #     - run:
  #         command: yarn build
  #         name: Build app
  #     - persist_to_workspace:
  #         root: ~/project
  #         paths:
  #           - .
  storybook:
    executor:
      name: node/default
      tag: '16.14.2'
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - 90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50
      - run:
          name: Add github to known_hosts
          command: |
            mkdir -p ~/.ssh/
            chmod 700 ~/.ssh/
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Publish storybook
          command: yarn run ci:storybook
          environment:
            NODE_DEBUG: gh-pages

# workflows:
#   build:
#     jobs:
#       - build:
#           context: default
#           filters:
#             branches:
#               only:
#                 - develop
#                 - /pull.*/
#       - unit_tests:
#           context: default
#           requires:
#             - build
#           filters:
#             branches:
#               only:
#                 - develop
#                 - /pull.*/
#       - storybook:
#           context: default
#           filters:
#             branches:
#               only:
#                 - develop
#                 - /pull.*/
#           requires:
#             - unit_tests

workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - unit_tests:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /pull.*/
