version: 2.1

commands:
  load_public_build:
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Load public image
          command: docker load -i sv_mosaic_build.tar

jobs:
  public_build:
    docker:
      - image: cimg/base:2021.04
        name: build
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Build public image
          command: DOCKER_BUILDKIT=1 docker build -t "sv-mosaic" .
      - run:
          name: Save public image
          command: docker save -o sv_mosaic_build.tar sv-mosaic
      - persist_to_workspace:
          root: ~/project
          paths:
            - sv_mosaic_build.tar
            - scripts
  private_build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export IMAGE="gcr.io/sv-shared-231700/sv-mosaic:${CIRCLE_BRANCH}"' >> $BASH_ENV
      - run:
          name: Docker build
          command: |
            docker login -u _json_key -p "${GCLOUD_SERVICE_KEY}" https://gcr.io
            docker pull $IMAGE || true
            DOCKER_BUILDKIT=1 docker build -t $IMAGE --cache-from $IMAGE .
            docker push $IMAGE
  unit_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - load_public_build
      - run:
          name: Spin up sub-container
          command: chmod +x ./scripts/run-capture-id && ./scripts/run-capture-id
      - run:
          name: Run tests
          command: docker exec $CONTAINER_ID yarn test:ci
      - run:
          name: Extract reports
          command: docker cp $CONTAINER_ID:/app/reports ~/reports
      - store_test_results:
          path: ~/reports
  e2e_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - load_public_build
      - run:
          name: Spin up test containers
          command: cd automation_testing && docker-compose up --detach
      - run:
          name: Copy tests to container
          command: |
            docker cp ./automation_testing sv-mosaic-e2e:/app/automation_testing
            docker exec sv-mosaic-e2e chmod +x automation_testing/scripts/try-storybook
            docker exec sv-mosaic-e2e mkdir /app/src
            docker cp ./src/theme sv-mosaic-e2e:/app/src/theme
      - run:
          name: List dir
          command: docker exec sv-mosaic-e2e ls -la ./automation_testing
      - run:
          name: Run tests
          command: docker exec sv-mosaic-e2e ./automation_testing/scripts/try-storybook
  storybook:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - load_public_build
      - add_ssh_keys:
          fingerprints:
            - 90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50
      - run:
          name: Add github to known_hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: List .ssh
          command: ls -la ~/.ssh
      - run:
          name: Spin up publishing container
          command: docker run --name sv-mosaic -e CIRCLE_BRANCH=${CIRCLE_BRANCH} -v ~/.ssh:/root/.ssh -it sv-mosaic sh -c "ssh-keyscan github.com >> ~/.ssh/known_hosts && yarn run ci:storybook"
      # - run:
      #     name: Publish storybook
      #     command: docker run --name sv-mosaic -it ls ~
      #     environment:
      #       NODE_DEBUG: gh-pages
  publish:
    docker:
      - image: gcr.io/sv-shared-231700/sv-mosaic:${CIRCLE_BRANCH}
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    working_directory: /app
    steps:
      - run:
          name: Publish to NPM
          command: yarn run ci:publish

workflows:
  build:
    jobs:
      - public_build:
          context: default
          filters:
            branches:
              only:
                - develop
                - /pull.*/
                - ci-testing
      - private_build:
          context: default
          filters:
            branches:
              only:
                - develop
                # - ci-testing
                - qa
                - staging
                - master
      - unit_tests:
          context: default
          requires:
            - public_build
          filters:
            branches:
              only:
                - develop
                - /pull.*/
                - ci-testing
      - e2e_tests:
          context: default
          requires:
            - public_build
          filters:
            branches:
              only:
                - develop
                - /pull.*/
                # - ci-testing
      - storybook:
          context: default
          requires:
            # - unit_tests
            # - e2e_tests
            - public_build
          filters:
            branches:
              only:
                - develop
                - ci-testing
                - qa
                - staging
                - master
      - publish:
          context: default
          requires:
            - unit_tests
            - e2e_tests
            - private_build
          filters:
            branches:
              only:
                # - ci-testing
                - qa
                - staging
                - master
