version: 2.1
workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - master
                - qa
                - staging
      - storybook:
          requires:
            - build
          context: default

orbs:
  slack: circleci/slack@4.4.0
jobs:
  storybook:
    docker:
      - image: gcr.io/sv-shared-231700/sv-mosaic:${CIRCLE_BRANCH}
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    working_directory: /app
    steps:
      - run:
          name: debug
          command: env
      - run:
          name: Publish storybook
          command: yarn run ci:storybook
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export IMAGE="gcr.io/sv-shared-231700/sv-mosaic:${CIRCLE_BRANCH}"' >> $BASH_ENV
      - run:
          name: Docker build
          command: |
            docker login -u _json_key -p "${GCLOUD_SERVICE_KEY}" https://gcr.io
            docker pull $IMAGE || true
            DOCKER_BUILDKIT=1 docker build -t $IMAGE --cache-from $IMAGE .
            docker push $IMAGE
      # - run:
      #     name: Prepublish NPM
      #     command: docker run -e CIRCLE_BRANCH -e CIRCLE_SHA1 sv-mosaic:local yarn run ci:prepublish
      # - slack/notify:
      #     channel: GT3L59FHP
      #     event: fail
      #     template: basic_fail_1
      # - slack/notify:
      #     channel: GT3L59FHP
      #     event: pass
      #     template: basic_success_1
